language: scala
sudo: false
scala:
  - 2.10.6
  - 2.11.8
  - 2.12.1
jdk:
  - oraclejdk7
  - oraclejdk8
script: sbt ++${TRAVIS_SCALA_VERSION} docs/paradox
matrix:
  exclude:
  - scala: 2.12.1
    jdk: oraclejdk7
